# Generated by Django 3.0.7 on 2020-06-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftpmonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='folder_name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
