# Generated by Django 3.0.7 on 2020-06-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftpmonitor', '0002_files_folder_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='authenticate',
            new_name='Auth',
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
